# Generated by Django 4.2.3 on 2023-07-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
