# Generated by Django 4.2.3 on 2023-07-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite',
        ),
    ]
