# Generated by Django 4.2.3 on 2023-07-04 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 5, 47, 30, 976176, tzinfo=datetime.timezone.utc)),
        ),
    ]
