# Generated by Django 4.2.3 on 2023-07-04 04:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("date", models.DateTimeField(verbose_name="date published")),
                ("body", models.TextField(verbose_name="Content")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("월요일", "월요일"),
                            ("화요일", "화요일"),
                            ("수요일", "수요일"),
                            ("목요일", "목요일"),
                            ("금요일", "금요일"),
                            ("토요일", "토요일"),
                            ("일요일", "일요일"),
                        ],
                        max_length=10,
                        verbose_name="week",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("comment_text", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="snippets.post",
                    ),
                ),
            ],
        ),
    ]
