# Generated by Django 4.2.3 on 2023-07-04 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0003_alter_post_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
